apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp

spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp

  template:
    metadata:
      labels:
        app: webapp

    spec:
      containers:
      - name: mongo-express   #name of container
        image: mongo-express:latest #name with version
        ports:
        - containerPort: 8081 #default port of container
        env:                             #extra lines added from secrets to refer env variables of username & Password of mongodb

          - name: ME_CONFIG_MONGODB_ADMINUSERNAME    #environment variable for mongo-express to connect with mongodb visit dockerhub
            valueFrom:
              secretKeyRef:
                name: mongo-secret  #name of metadata
                key: mongo-user #key used for storing value ie username

          - name: ME_CONFIG_MONGODB_ADMINPASSWORD  #environment variable for mongoexpress to connect with mongodb mongo-e password
            valueFrom:
              secretKeyRef:
                name: mongo-secret  #name of metadata 
                key: mongo-password #key used for storing value ie password

          - name: ME_CONFIG_MONGODB_SERVER  #environment variable for mongoexpress to connect with mongodb mongo-e password
            valueFrom:
              configMapRef:
                name: mongo-config  #name of file
                key: mongo-url #key used for storing value ie password          



---

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp     #this app name connects the service with the deployment
  ports:
    - protocol: TCP
      port: 8081 #can be same port or different 
      targetPort: 8081 #same port as mongodb containerport
      nodePort: 30200
    